//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProje_MuratYucedag.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLKategoriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKategoriler()
        {
            this.TBLUrunler = new HashSet<TBLUrunler>();
        }
        [DisplayName("Kategori Id")]
        public short KategoriId { get; set; }

        [DisplayName("Kategori Adý"),Required(ErrorMessage = "Kategori adý boþ geçilemez..")]
        public string KategoriAd { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLUrunler> TBLUrunler { get; set; }
    }
}
